CREATE TABLE dbo.Customer (
    CustomerId INT IDENTITY(1, 1),
    FirstName NVARCHAR(50) NOT NULL,
    LastName NVARCHAR(50) NOT NULL,
    CreatedBy NVARCHAR(50) NOT NULL,
    UpdatedBy NVARCHAR(50) NULL,
    ValidFrom DATETIME2(0) GENERATED ALWAYS AS ROW START HIDDEN NOT NULL CONSTRAINT [DF_Customer_ValidFrom] DEFAULT SYSUTCDATETIME(),
    ValidTo DATETIME2(0) GENERATED ALWAYS AS ROW END HIDDEN NOT NULL CONSTRAINT [DF_Customer_ValidTo] DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
    CONSTRAINT PK_Customer PRIMARY KEY (CustomerId),
    PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo)
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.CustomerHistory));
