CREATE TABLE dbo.Customer (
    CustomerId INT IDENTITY(1, 1),
    FirstName NVARCHAR(50) NOT NULL,
    LastName NVARCHAR(50) NOT NULL,
    CreatedAt DATETIME2(0) DEFAULT SYSDATETIME(),
    CreatedBy NVARCHAR(50) DEFAULT SUSER_NAME(),
    UpdatedAt DATETIME2(0) DEFAULT SYSDATETIME(),
    UpdatedBy NVARCHAR(50) DEFAULT SUSER_NAME(),
    CONSTRAINT PK_Customer PRIMARY KEY (CustomerId)
);